ALTER TABLE public.webinars
  ADD COLUMN IF NOT EXISTS reg_form_secrets jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS reg_form_qualifiers_for jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS reg_form_qualifiers_not_for jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS reg_form_results jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS reg_form_bonuses jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS reg_form_show_countdown boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS reg_form_countdown_seconds integer DEFAULT 6137,
  ADD COLUMN IF NOT EXISTS reg_form_show_viewer_count boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS reg_form_show_spots_left boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS reg_form_spots_left integer DEFAULT 17,
  ADD COLUMN IF NOT EXISTS reg_form_secondary_timezone text DEFAULT 'Asia/Dubai',
  ADD COLUMN IF NOT EXISTS reg_form_accent_color text DEFAULT '#f7c948',
  ADD COLUMN IF NOT EXISTS reg_form_urgency_bar_text text DEFAULT '⚠️ SEATS ARE LIMITED — Registration closing soon',
  ADD COLUMN IF NOT EXISTS reg_form_show_urgency_bar boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS reg_form_bonuses_total_value text DEFAULT '$891';